import '../model/base_breed_model.dart';

class BaseBreedController {
  List<BaseBreed> getBreeds(String category) {
    switch (category) {
      case 'Dog':
        return [
          BaseBreed(
            name: 'German Shepherd',
            imageUrl:'assets/images/dogs/german.jpg',
            size: 'Large breed;',
            lifespan: 'lifespan of 9–13 years.',
            temperament: 'Loyal, intelligent, protective; can be friendly if socialized well.',
            healthIssues: 'Prone to hip & elbow dysplasia, bloat, degenerative myelopathy.',
            groomingNeeds: 'Moderate to high; sheds a lot, needs regular brushing.',
            dietNutrition: 'High-protein diet needed; can suffer from food allergies.',
            exerciseRequirements: 'Very high; needs at least 1–2 hours of daily exercise.',
            trainabilityIntelligence: 'Highly intelligent & easy to train; used in police & military work.',
            climateSuitability: 'Adapts well to moderate to cool climates; struggles in extreme heat.',
            apartmentSpaceNeeds: 'Not ideal for apartments; needs a large area to move around.',
            purposeSuitability: 'Great for guarding, security, and active families; requires experienced handling.',
            adoptionBuying: 'Buying is expensive; better suited for those who can handle their exercise and training needs.',
          ),BaseBreed(
            name: 'Chow Chow',
            imageUrl: 'assets/images/dogs/chow.jpg',
            size: 'Medium to large breed',
            lifespan: 'Lifespan of 8–12 years.',
            temperament: 'Independent, aloof, loyal, and sometimes stubborn; not overly affectionate but protective of family.',
            healthIssues: 'Prone to hip dysplasia, entropion (eye condition), and hypothyroidism.',
            groomingNeeds: 'High maintenance; dense double coat requires regular brushing to prevent matting and shedding.',
            dietNutrition: 'Balanced diet required; prone to obesity if overfed.',
            exerciseRequirements: 'Moderate; needs at least 30–60 minutes of exercise daily.',
            trainabilityIntelligence: 'Independent and intelligent; training can be challenging due to their stubborn nature.',
            climateSuitability: 'Adapts to cooler climates; struggles in hot weather due to thick coat.',
            apartmentSpaceNeeds: 'Can adapt to apartments, but needs regular exercise and space to move around.',
            purposeSuitability: 'Ideal companion dog; not suitable for guarding or high-energy work.',
            adoptionBuying: 'Buying is more common, but adoption is a good option for experienced owners.',
          ),
          BaseBreed(
            name: 'Bulldog',
            imageUrl:'assets/images/dogs/bulldog.jpg',
            size: 'Medium breed',
            lifespan: 'lifespan of 8–12 years.',
            temperament: 'Calm, courageous, friendly, and affectionate; great companion.',
            healthIssues: 'Prone to respiratory issues, hip dysplasia, and obesity.',
            groomingNeeds: 'Low to moderate; short coat requires occasional brushing.',
            dietNutrition: 'Well-balanced diet; prone to obesity, so portion control is important.',
            exerciseRequirements: 'Low to moderate; needs short walks and minimal exercise.',
            trainabilityIntelligence: 'Stubborn but intelligent; requires consistent, patient training.',
            climateSuitability: 'Struggles in hot climates; prefers cooler temperatures.',
            apartmentSpaceNeeds: 'Well-suited for apartments; low energy makes them ideal for small living spaces.',
            purposeSuitability: 'Ideal family pet; not suitable for guarding or working roles.',
            adoptionBuying: 'Buying is common, but adoption is an excellent choice due to their popularity.',
          ),
          BaseBreed(
            name: 'Labrador Retriever',
            imageUrl:'assets/images/dogs/labraa.jpg',
            size: 'Medium to large breed',
            lifespan: 'lifespan of 10–14 years.',
            temperament: 'Friendly, affectionate, intelligent, and social; great with families and kids.',
            healthIssues: 'Prone to hip & elbow dysplasia, obesity, and ear infections.',
            groomingNeeds: 'Moderate; short coat but sheds a lot, requires regular brushing.',
            dietNutrition: 'Balanced diet needed; prone to overeating, so portion control is important.',
            exerciseRequirements: 'Moderate to high; needs at least 1–2 hours of daily activity.',
            trainabilityIntelligence: 'Highly intelligent & easy to train; often used as service and therapy dogs.',
            climateSuitability: 'Adapts well to most climates, but prefers moderate temperatures.',
            apartmentSpaceNeeds: 'Can adapt to apartments if exercised well, but prefers open spaces.',
            purposeSuitability: 'Great family pet, therapy dog, guide dog, and companion; not ideal for guarding.',
            adoptionBuying: 'Widely available for adoption; better to adopt if looking for a pet rather than a show dog.',
          ),
          BaseBreed(
            name: 'Rottweiler',
            imageUrl:'assets/images/dogs/rott.jpg',
            size: 'Large breed;',
            lifespan: 'lifespan of 9–12 years.',
            temperament: 'Loyal, confident, protective, and intelligent.',
            healthIssues: 'Prone to hip & elbow dysplasia, heart disease, and obesity.',
            groomingNeeds: 'Low maintenance; short coat requires occasional brushing.',
            dietNutrition: 'High-protein diet required; prone to overeating, so portion control is necessary.',
            exerciseRequirements: 'High; needs at least 1.5–2 hours of daily activity.',
            trainabilityIntelligence: 'Highly trainable but needs firm leadership.',
            climateSuitability: 'Handles moderate to cool climates better; struggles in extreme heat.',
            apartmentSpaceNeeds: 'Not ideal for apartments; needs space to move around.',
            purposeSuitability: 'Excellent guard dog, family protector, and working dog.',
            adoptionBuying: 'Buying is common, but adoption is a good option if experienced with large, powerful breeds.',
          ),
          BaseBreed(
            name: 'Beagle',
            imageUrl:'assets/images/dogs/beagle.jpg',
            size: 'Small to medium breed',
            lifespan: 'lifespan of 12–15 years.',
            temperament: 'Friendly, curious, energetic, and playful.',
            healthIssues: 'Prone to obesity, ear infections, epilepsy, and hip dysplasia.',
            groomingNeeds: 'Low maintenance; short coat requires occasional brushing.',
            dietNutrition: 'Balanced diet required; prone to overeating.',
            exerciseRequirements: 'Moderate; needs at least 1 hour of daily activity.',
            trainabilityIntelligence: 'Smart but stubborn; needs patience and consistency in training.',
            climateSuitability: 'Adapts well to most climates, but struggles in extreme heat.',
            apartmentSpaceNeeds: 'Well-suited for apartments, but requires regular outdoor walks.',
            purposeSuitability: 'Great family pet, hunting dog, and companion.',
            adoptionBuying: 'Commonly available for adoption; adoption is a good choice for families.',
          ),
        ];
      case 'Cat':
        return [
          BaseBreed(
            name: 'Persian',
            imageUrl:'assets/images/cats/persian.jpg',
            size: 'Medium-sized',
            lifespan: '12–16 years',
            temperament: 'Calm, affectionate, and independent; can be reserved but loves attention.',
            healthIssues: 'Prone to respiratory issues, dental problems, and kidney disease.',
            groomingNeeds: 'High maintenance; long, thick coat requires daily brushing.',
            dietNutrition: 'Balanced diet required; may have a tendency to overeat.',
            exerciseRequirements: 'Low; prefers lounging but still needs occasional playtime.',
            trainabilityIntelligence: 'Intelligent but may be less eager to please.',
            climateSuitability: 'Not well-suited for hot climates.',
            apartmentSpaceNeeds: 'Well-suited for apartment living.',
            purposeSuitability: 'Great lap cat and companion.',
            adoptionBuying: 'Available for adoption.',
          ),
          BaseBreed(
            name: 'British Shorthair',
            size: 'Medium to large',
            imageUrl:'assets/images/cats/shorthair.jpg',
            lifespan: '12–20 years',
            temperament: 'Calm, independent, and affectionate.',
            healthIssues: 'Prone to heart disease, dental problems, and obesity.',
            groomingNeeds: 'Low maintenance; occasional brushing.',
            dietNutrition: 'Balanced diet required; monitor to avoid overeating.',
            exerciseRequirements: 'Moderate; enjoys playtime but is content lounging.',
            trainabilityIntelligence: 'Intelligent and easy to train, but independent.',
            climateSuitability: 'Adapts well to various climates.',
            apartmentSpaceNeeds: 'Well-suited for apartment living.',
            purposeSuitability: 'Ideal companion cat.',
            adoptionBuying: 'Available for adoption.',
          ),
          BaseBreed(
            name: 'British Longhair',
            imageUrl:'assets/images/cats/longhair.jpg',
            size: 'Medium to large',
            lifespan: '12–16 years',
            temperament: 'Calm, gentle, and affectionate.',
            healthIssues: 'Prone to heart disease, dental issues, and obesity.',
            groomingNeeds: 'High maintenance; regular brushing required.',
            dietNutrition: 'Balanced diet required; portion control is important.',
            exerciseRequirements: 'Moderate; enjoys playtime and interactive toys.',
            trainabilityIntelligence: 'Intelligent but independent.',
            climateSuitability: 'Prefers cooler, moderate temperatures.',
            apartmentSpaceNeeds: 'Well-suited for apartment living.',
            purposeSuitability: 'Ideal companion cat.',
            adoptionBuying: 'Available for adoption.',
          ),
          BaseBreed(
            name: 'Scottish Fold',
            imageUrl:'assets/images/cats/foldd.jpg',
            size: 'Medium-sized',
            lifespan: '11–15 years',
            temperament: 'Sweet, calm, and affectionate.',
            healthIssues: 'Prone to joint problems and heart disease.',
            groomingNeeds: 'Low to moderate maintenance.',
            dietNutrition: 'Balanced diet required; portion control is important.',
            exerciseRequirements: 'Low to moderate; enjoys playing but is more laid-back.',
            trainabilityIntelligence: 'Intelligent and learns quickly.',
            climateSuitability: 'Adapts well to moderate climates.',
            apartmentSpaceNeeds: 'Well-suited for apartment living.',
            purposeSuitability: 'Ideal companion cat.',
            adoptionBuying: 'Available for adoption.',
          ),
          BaseBreed(
            name: 'Bombay Cat',
            imageUrl:'assets/images/cats/bombay.jpg',
            size: 'Medium-sized',
            lifespan: '12–16 years',
            temperament: 'Affectionate, playful, and confident.',
            healthIssues: 'Prone to respiratory issues, heart disease, and obesity.',
            groomingNeeds: 'Low maintenance; minimal brushing.',
            dietNutrition: 'Balanced diet required; portion control is important.',
            exerciseRequirements: 'Moderate; enjoys interactive play.',
            trainabilityIntelligence: 'Highly intelligent and easy to train.',
            climateSuitability: 'Adapts well to moderate climates.',
            apartmentSpaceNeeds: 'Well-suited for apartment living.',
            purposeSuitability: 'Ideal companion cat.',
            adoptionBuying: 'Available for adoption.',
          ),
          BaseBreed(
            imageUrl:'assets/images/cats/ragdoll.JPG',
            name: 'Ragdoll',
            size: 'Large',
            lifespan: '12–15 years',
            temperament: 'Gentle, affectionate, and calm.',
            healthIssues: 'Prone to heart disease, kidney problems, and obesity.',
            groomingNeeds: 'Moderate maintenance; semi-long coat requires regular brushing.',
            dietNutrition: 'Balanced diet required; monitor for overeating.',
            exerciseRequirements: 'Moderate; enjoys playing but is more relaxed.',
            trainabilityIntelligence: 'Highly intelligent and trainable.',
            climateSuitability: 'Adapts well to moderate climates.',
            apartmentSpaceNeeds: 'Well-suited for apartment living.',
            purposeSuitability: 'Ideal companion cat.',
            adoptionBuying: 'Available for adoption.',
          ),
          BaseBreed(
            name: 'Sphynx cat',
            imageUrl:'assets/images/cats/sphynxx.jpg',
            size: 'Medium-sized',
            lifespan: '12–16 years',
            temperament: 'Affectionate, energetic, and curious.',
            healthIssues: 'Prone to skin problems, heart disease, and temperature regulation issues.',
            groomingNeeds: 'High maintenance; regular baths needed.',
            dietNutrition: 'Balanced diet required; higher metabolism.',
            exerciseRequirements: 'High; very active and playful.',
            trainabilityIntelligence: 'Highly intelligent and trainable.',
            climateSuitability: 'Not suitable for cold climates.',
            apartmentSpaceNeeds: 'Well-suited for apartment living.',
            purposeSuitability: 'Ideal companion cat.',
            adoptionBuying: 'Available for adoption.',
          ),
        ];
      case 'Bird':
        return [

             BaseBreed(
    name: "Parrot",
    imageUrl: "assets/images/birds/parrot.jpg",
    size: "Varies by species",
    lifespan: "10–80 years",
    temperament: "Affectionate, energetic, and social",
    healthIssues: "Prone to feather plucking, respiratory issues, and obesity",
    groomingNeeds: "Moderate; requires feather care, nail trimming, and beak maintenance",
    dietNutrition: "Balanced diet of pellets, fruits, vegetables, and occasional seeds",
    exerciseRequirements: "High; need regular physical and mental stimulation",
    trainabilityIntelligence: "Highly intelligent and trainable",
    apartmentSpaceNeeds: "Suitable for apartment living if given adequate space and interaction",
    climateSuitability: "Best suited for warm climates",
    purposeSuitability: "Ideal companion pet; not suited for those unable to commit to their care",
    adoptionBuying: "Available for adoption, a great option for providing a forever home",
  ),
  BaseBreed(
    name: "Cockatiel",
    imageUrl: "assets/images/birds/cockatiel.jpg",
    size: "Small to medium-sized",
    lifespan: "10–20 years",
    temperament: "Friendly, affectionate, and playful",
    healthIssues: "Prone to respiratory issues, feather plucking, and obesity",
    groomingNeeds: "Low to moderate; requires regular feather care, nail trimming, and beak maintenance",
    dietNutrition: "Balanced diet of pellets, seeds, fruits, and vegetables",
    exerciseRequirements: "Moderate to high; need daily stimulation",
    trainabilityIntelligence: "Intelligent and trainable",
    apartmentSpaceNeeds: "Well-suited for apartment living",
    climateSuitability: "Best suited for moderate climates",
    purposeSuitability: "Ideal companion pet; perfect for families and singles",
    adoptionBuying: "Available for adoption, a great option for providing a loving home",
  ),
  BaseBreed(
    name: "Hyacinth Macaw",
    imageUrl: "assets/images/birds/hyacinath.jpg",
    size: "Large breed",
    lifespan: "50–60 years",
    temperament: "Affectionate, playful, and intelligent",
    healthIssues: "Prone to feather plucking, heart disease, and respiratory issues",
    groomingNeeds: "Moderate; requires regular feather maintenance and beak care",
    dietNutrition: "Varied diet of high-quality pellets, nuts, seeds, fruits, and vegetables",
    exerciseRequirements: "High; need daily physical and mental exercise",
    trainabilityIntelligence: "Highly intelligent and trainable",
    apartmentSpaceNeeds: "Not well-suited for apartment living; need a large aviary or open space",
    climateSuitability: "Best suited for warm climates",
    purposeSuitability: "Ideal for experienced bird owners",
    adoptionBuying: "Available for adoption, though often expensive",
  ),
  BaseBreed(
    name: "Lovebird",
    imageUrl: "assets/images/birds/lovebird.jpg",
    size: "Small breed",
    lifespan: "10–15 years",
    temperament: "Affectionate, social, and playful",
    healthIssues: "Prone to respiratory infections, feather plucking, and obesity",
    groomingNeeds: "Low to moderate; requires regular beak care, nail trimming, and occasional baths",
    dietNutrition: "Balanced diet of pellets, seeds, fruits, and vegetables",
    exerciseRequirements: "Moderate to high; active and enjoy flying and climbing",
    trainabilityIntelligence: "Intelligent and trainable",
    apartmentSpaceNeeds: "Well-suited for apartment living; require a cage with space",
    climateSuitability: "Best suited for moderate climates",
    purposeSuitability: "Ideal companion pet; perfect for people looking for a small, social bird",
    adoptionBuying: "Available for adoption, a great option for those looking to provide a loving home",
  ),
  BaseBreed(
    name: "Scarlet Macaw",
    imageUrl: "assets/images/birds/scarlet.jpg",
    size: "Large breed",
    lifespan: "40–50 years",
    temperament: "Affectionate, intelligent, and playful",
    healthIssues: "Prone to feather plucking, obesity, and respiratory issues",
    groomingNeeds: "Moderate; requires regular beak and nail trimming",
    dietNutrition: "Requires a varied diet of pellets, seeds, nuts, fruits, and vegetables",
    exerciseRequirements: "High; need daily physical and mental exercise",
    trainabilityIntelligence: "Highly intelligent and trainable",
    apartmentSpaceNeeds: "Not ideal for apartment living; requires ample space",
    climateSuitability: "Best suited for warm climates",
    purposeSuitability: "Ideal companion for experienced bird owners",
    adoptionBuying: "Available for adoption, often expensive",
  ),
  BaseBreed(
    name: "Columbidae (Pigeon/Dove)",
    imageUrl: "assets/images/birds/pigeon.jpg",
    size: "Medium-sized birds",
    lifespan: "5–15 years",
    temperament: "Gentle, peaceful, and social",
    healthIssues: "Prone to respiratory infections, parasites, and obesity",
    groomingNeeds: "Low; require regular cage cleaning and occasional nail trimming",
    dietNutrition: "Diet of seeds, grains, and occasional fruits and vegetables",
    exerciseRequirements: "Moderate; need space to fly and exercise",
    trainabilityIntelligence: "Moderate intelligence; can learn simple tricks",
    apartmentSpaceNeeds: "Suitable for apartment living if given adequate space",
    climateSuitability: "Best suited for temperate climates",
    purposeSuitability: "Ideal for low-maintenance, calm companionship",
    adoptionBuying: "Available for adoption from rescues or sanctuaries",
  ),
  BaseBreed(
    name: "House Sparrow",
    imageUrl: "assets/images/birds/sparrow.jpg",
    size: "Small breed",
    lifespan: "3–5 years in the wild",
    temperament: "Social, active, and curious",
    healthIssues: "Prone to respiratory infections, mites, and parasites",
    groomingNeeds: "Low; generally self-sufficient in grooming",
    dietNutrition: "Primarily seeds, grains, and fruits",
    exerciseRequirements: "Moderate; need space to move and fly",
    trainabilityIntelligence: "Moderate intelligence; adaptable to their environment",
    apartmentSpaceNeeds: "Can be kept in a large indoor aviary or protected outdoor area",
    climateSuitability: "Best suited for temperate climates",
    purposeSuitability: "Ideal for bird enthusiasts looking for a low-maintenance pet",
    adoptionBuying: "Can be adopted from local rescues or rehabilitated if wild-caught",
  ),
  ];
   case 'Aquatic':
        return [
           BaseBreed(
            name: 'Goldfish',
            imageUrl: 'assets/images/fish/goldfish.jpg',
            size: '15-30 cm',
            lifespan: '10-20+ years',
            temperament: 'Peaceful, but can be territorial',
            healthIssues: 'Prone to swim bladder disease and goldfish granuloma',
            groomingNeeds: 'Low; regular water changes and tank cleaning',
            dietNutrition: 'High-quality pellets, flakes, and occasional fresh veggies',
            exerciseRequirements: 'Requires swimming space, avoid overcrowding',
            trainabilityIntelligence: 'Moderate; can be trained to follow food',
            apartmentSpaceNeeds: 'Requires a minimum 75L tank for one, 40L for each additional',
            climateSuitability: 'Coldwater; ideal temp 18-22°C',
            purposeSuitability: 'Ornamental',
            adoptionBuying: 'Available in pet stores, requires long-term commitment',
          ),
          BaseBreed(
            name: 'Siamese Fighting Fish (Betta)',
            imageUrl: 'assets/images/fish/betta.jpg',
            size: '6-8 cm',
            lifespan: '3-5 years',
            temperament: 'Aggressive, territorial',
            healthIssues: 'Can develop fin rot, swim bladder issues',
            groomingNeeds: 'Low; clean water and regular tank maintenance',
            dietNutrition: 'High-protein pellets, frozen/live food (bloodworms, brine shrimp)',
            exerciseRequirements: 'Needs space to swim, avoid strong currents',
            trainabilityIntelligence: 'Moderate; can recognize owners and learn simple tricks',
            apartmentSpaceNeeds: 'Minimum 10 liters, 20+ liters is ideal',
            climateSuitability: 'Warm water; ideal temp 24-28°C',
            purposeSuitability: 'Ornamental, pet',
            adoptionBuying: 'Readily available, easy to care for in suitable conditions',
          ),
          BaseBreed(
            name: 'Guppy',
            imageUrl: 'assets/images/fish/guppy.jpg',
            size: '4-6 cm',
            lifespan: '2-3 years',
            temperament: 'Peaceful and social',
            healthIssues: 'Prone to tail rot and fin nipping',
            groomingNeeds: 'Low; regular water changes and keeping water parameters stable',
            dietNutrition: 'Flakes, pellets, live/frozen food (brine shrimp, bloodworms)',
            exerciseRequirements: 'Moderate; enjoys swimming in groups',
            trainabilityIntelligence: 'Low; basic care needs',
            apartmentSpaceNeeds: 'Minimum 40L for small group (3-5 guppies)',
            climateSuitability: 'Warm water; ideal temp 22-28°C',
            purposeSuitability: 'Ornamental, pet',
            adoptionBuying: 'Affordable and widely available in pet stores',
          ),
          BaseBreed(
            name: 'Tetra',
            imageUrl: 'assets/images/fish/tetra.jpg',
            size: '3-5 cm',
            lifespan: '3-5 years',
            temperament: 'Peaceful, schooling fish',
            healthIssues: 'Prone to stress if kept alone, can develop swim bladder issues',
            groomingNeeds: 'Low; regular water changes and water parameter monitoring',
            dietNutrition: 'High-quality flakes, small pellets, live/frozen food (brine shrimp, bloodworms)',
            exerciseRequirements: 'Needs to be kept in schools (6+); requires swimming space',
            trainabilityIntelligence: 'Low; requires basic care and attention',
            apartmentSpaceNeeds: 'Minimum 40L for a small school of tetras',
            climateSuitability: 'Warm water; ideal temp 22-26°C',
            purposeSuitability: 'Community fish, ornamental',
            adoptionBuying: 'Common in pet stores, often available in schools',
          ),
          BaseBreed(
            name: 'Catfish',
            imageUrl: 'assets/images/fish/catfish.jpg',
            size: '5 cm to over 50 cm, depending on species',
            lifespan: '3-5 years (small species), 10+ years (large species)',
            temperament: 'Peaceful, bottom-dwellers',
            healthIssues: 'Prone to poor water conditions, possible injuries from sharp decorations',
            groomingNeeds: 'Moderate; clean tank regularly and check water parameters',
            dietNutrition: 'Sinking pellets, algae wafers, occasional live/frozen food',
            exerciseRequirements: 'Requires space at the bottom of the tank, hides in caves or plants',
            trainabilityIntelligence: 'Low; basic care requirements',
            apartmentSpaceNeeds: '40+ liters for small species, 100+ liters for large species',
            climateSuitability: 'Warm water; ideal temp 22-28°C',
            purposeSuitability: 'Community fish, bottom dwellers',
            adoptionBuying: 'Available in pet stores; consider species-specific care needs',
          ),
          BaseBreed(
            name: 'Turtle',
            imageUrl: 'assets/images/fish/turtle.jpg',
            size: '15-30 cm, depending on species',
            lifespan: '20-50+ years',
            temperament: 'Calm but can be solitary',
            healthIssues: 'Prone to shell rot and respiratory infections',
            groomingNeeds: 'High; clean tank regularly and monitor for diseases',
            dietNutrition: 'Pellets, vegetables, occasional live food (worms, insects)',
            exerciseRequirements: 'Needs a large tank with basking area and water space',
            trainabilityIntelligence: 'Low; can recognize owners but not very interactive',
            apartmentSpaceNeeds: 'Requires 75-150L for small turtles, larger species need more space',
            climateSuitability: 'Warm water; basking area needs 30-35°C with UVB light',
            purposeSuitability: 'Pet, ornamental',
            adoptionBuying: 'Consider legal ownership; requires long-term care and maintenance',
          ),
        ];
      case 'Others':
        return [

            BaseBreed(
            name: 'Rabbit',
            imageUrl: 'assets/images/others/rabbit.png', // Replace with actual image URL
            size: '1-6+ kg (varies by breed)',
            lifespan: '8-12 years',
            temperament: 'Social, prefers gentle handling',
            healthIssues: 'Prone to dental and digestive problems, requires regular vet checkups',
            groomingNeeds: 'Regular brushing, especially for long-haired breeds',
            dietNutrition: '80% hay, fresh veggies, limited pellets, avoid sugary treats',
            exerciseRequirements: 'Requires 3-4 hours of daily exercise outside the cage',
            trainabilityIntelligence: 'Can be litter-box trained with patience',
            apartmentSpaceNeeds: 'Needs a large cage (min 1.5m²) or free-roaming area',
            climateSuitability: 'Indoor living recommended, needs temperature control',
            purposeSuitability: 'Great companion pet, requires time and attention',
            adoptionBuying: 'Requires long-term commitment and care, including regular vet visits',
          ),
          // Guinea Pigs
          BaseBreed(
            name: 'Guinea Pig',
            imageUrl: 'assets/images/others/guinea.png', // Replace with actual image URL
            size: '20-30 cm long',
            lifespan: '5-7 years',
            temperament: 'Highly social, vocal, and expressive',
            healthIssues: 'Prone to dental, respiratory, and digestive issues, needs regular checkups',
            groomingNeeds: 'Short-haired breeds need little grooming, long-haired need regular brushing',
            dietNutrition: '80% hay, fresh vegetables, vitamin C-rich food, and limited pellets',
            exerciseRequirements: 'Needs 3-4 hours of floor time daily in a safe area',
            trainabilityIntelligence: 'Can be trained to use a specific area but not fully litter-box trained',
            apartmentSpaceNeeds: 'Minimum 0.7m² per guinea pig, no wire floors',
            climateSuitability: 'Indoor living recommended, requires temperature control',
            purposeSuitability: 'Great companion pet, ideal in pairs or groups',
            adoptionBuying: 'Moderate to high cost, requires time and care',
          ),
          // Hamsters
          BaseBreed(
            name: 'Hamster',
            imageUrl: 'assets/images/others/hamster.png', // Replace with actual image URL
            size: '5-18 cm (depending on species)',
            lifespan: '2-3 years',
            temperament: 'Nocturnal, dislikes sudden handling, can be tamed with patience',
            healthIssues: 'Prone to respiratory infections, tumors, and obesity, requires vet care',
            groomingNeeds: 'Generally self-grooming, sand baths help maintain cleanliness',
            dietNutrition: 'High-quality hamster pellets, fresh vegetables, occasional treats',
            exerciseRequirements: 'Needs a large running wheel (min 20 cm diameter) and playtime outside the cage',
            trainabilityIntelligence: 'Can be trained to use a specific potty corner in the cage',
            apartmentSpaceNeeds: 'Minimum 450 sq. inches (2900 cm²) of floor space',
            climateSuitability: 'Indoor living, avoid extreme temperatures',
            purposeSuitability: 'Ideal for small living spaces, requires regular interaction and care',
            adoptionBuying: 'Low cost but requires regular care, cleaning, and interaction',
          ),

        ];
      default:
        return [];
    }
  }
}
