name: pet_care_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get: ^4.7.2
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.2
  firebase_core: ^3.6.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  custom_rating_bar: ^3.0.0
  fluttertoast: ^8.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  get_storage: ^2.1.1
  flutter_rating_bar: ^4.0.1
  timeago: ^3.2.2
  firebase_messaging: ^15.2.3
  awesome_notifications: ^0.10.1
  awesome_notifications_fcm: ^0.10.1
  razorpay_flutter: ^1.3.7
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/birds/
    - assets/images/cats/
    - assets/images/dogs/
    - assets/images/fish/
    - assets/images/others/
    - assets/images/admin/
  # fonts:
  #   - family: Fredoka
  #     fonts:
  #       - asset: assets/fonts/Fredoka-Regular.ttf
  #       - asset: assets/fonts/Fredoka-Bold.ttf
  #         weight: 700
