name: pet_care_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Fredoka
  #     fonts:
  #       - asset: assets/fonts/Fredoka-Regular.ttf
  #       - asset: assets/fonts/Fredoka-Bold.ttf
  #         weight: 700
