// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp_f_NDbKeq2ooO59GzslsJhAohxOlKts',
    appId: '1:663906016335:web:58a1caed2c5f28d7111e3a',
    messagingSenderId: '663906016335',
    projectId: 'petcare-app-project',
    authDomain: 'petcare-app-project.firebaseapp.com',
    storageBucket: 'petcare-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEuMBvsGWAAHExSdygkbWr9l6fia0TIj8',
    appId: '1:663906016335:android:1da13b75a5d40129111e3a',
    messagingSenderId: '663906016335',
    projectId: 'petcare-app-project',
    storageBucket: 'petcare-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHyGH2VFmtGKxphMfsf_dj2L_amYHlc0',
    appId: '1:663906016335:ios:9cfbc26eb8c4f198111e3a',
    messagingSenderId: '663906016335',
    projectId: 'petcare-app-project',
    storageBucket: 'petcare-app-project.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcHyGH2VFmtGKxphMfsf_dj2L_amYHlc0',
    appId: '1:663906016335:ios:9cfbc26eb8c4f198111e3a',
    messagingSenderId: '663906016335',
    projectId: 'petcare-app-project',
    storageBucket: 'petcare-app-project.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp_f_NDbKeq2ooO59GzslsJhAohxOlKts',
    appId: '1:663906016335:web:6988c54a6eddd4ef111e3a',
    messagingSenderId: '663906016335',
    projectId: 'petcare-app-project',
    authDomain: 'petcare-app-project.firebaseapp.com',
    storageBucket: 'petcare-app-project.firebasestorage.app',
  );
}
