// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCarMxpK5SsKAMQwhcD_u1WV1x9I3lkDuk',
    appId: '1:1095557243603:web:8ae2ff9faffe84428aea26',
    messagingSenderId: '1095557243603',
    projectId: 'pet-care-app-project',
    authDomain: 'pet-care-app-project.firebaseapp.com',
    storageBucket: 'pet-care-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ9m2tSZnLTP9eKQNvffIxHUMN9eVnM_g',
    appId: '1:1095557243603:android:3921f8f4f35371fc8aea26',
    messagingSenderId: '1095557243603',
    projectId: 'pet-care-app-project',
    storageBucket: 'pet-care-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkV2Q6dAW1H9p0ZeH-gMbPM33Im8j_a5U',
    appId: '1:1095557243603:ios:f0624492238a9a578aea26',
    messagingSenderId: '1095557243603',
    projectId: 'pet-care-app-project',
    storageBucket: 'pet-care-app-project.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkV2Q6dAW1H9p0ZeH-gMbPM33Im8j_a5U',
    appId: '1:1095557243603:ios:f0624492238a9a578aea26',
    messagingSenderId: '1095557243603',
    projectId: 'pet-care-app-project',
    storageBucket: 'pet-care-app-project.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCarMxpK5SsKAMQwhcD_u1WV1x9I3lkDuk',
    appId: '1:1095557243603:web:e555ff2e0c1a0d368aea26',
    messagingSenderId: '1095557243603',
    projectId: 'pet-care-app-project',
    authDomain: 'pet-care-app-project.firebaseapp.com',
    storageBucket: 'pet-care-app-project.firebasestorage.app',
  );

}