// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9KU8BHNiu1GtOQ-4WT6RSVGxLagoGl2k',
    appId: '1:726567938075:web:555f8b48a23dba777f70be',
    messagingSenderId: '726567938075',
    projectId: 'project-petcare-app',
    authDomain: 'project-petcare-app.firebaseapp.com',
    storageBucket: 'project-petcare-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_XaM7d_MLIfMHW6jmtsf8HyQTTa_LZc',
    appId: '1:726567938075:android:ab9d846a13f7985a7f70be',
    messagingSenderId: '726567938075',
    projectId: 'project-petcare-app',
    storageBucket: 'project-petcare-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmq-XdS21hzDfppXmH5ltEgIMDVr_sDZU',
    appId: '1:726567938075:ios:118f4e3003cb28037f70be',
    messagingSenderId: '726567938075',
    projectId: 'project-petcare-app',
    storageBucket: 'project-petcare-app.firebasestorage.app',
    androidClientId: '726567938075-a9qdqf9l7s3co16a7re08h782tefepkd.apps.googleusercontent.com',
    iosClientId: '726567938075-n5i785s2ffsclpq4cmri2dv125rm0ne2.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmq-XdS21hzDfppXmH5ltEgIMDVr_sDZU',
    appId: '1:726567938075:ios:118f4e3003cb28037f70be',
    messagingSenderId: '726567938075',
    projectId: 'project-petcare-app',
    storageBucket: 'project-petcare-app.firebasestorage.app',
    androidClientId: '726567938075-a9qdqf9l7s3co16a7re08h782tefepkd.apps.googleusercontent.com',
    iosClientId: '726567938075-n5i785s2ffsclpq4cmri2dv125rm0ne2.apps.googleusercontent.com',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9KU8BHNiu1GtOQ-4WT6RSVGxLagoGl2k',
    appId: '1:726567938075:web:37c2fc494490c64d7f70be',
    messagingSenderId: '726567938075',
    projectId: 'project-petcare-app',
    authDomain: 'project-petcare-app.firebaseapp.com',
    storageBucket: 'project-petcare-app.firebasestorage.app',
  );

}